def sandwich():
    print("Open bag of bread.")
    print("Take two slices of bread")
    print("Get lettuce")
    print("Get tomato")
    print("Get Cheese slices")
    print("Get Jar of Mayonnaise")
    print("Get a knife")
    print("Cut Lettuce into slices")
    print("Put away lettuce")
    print("Wash knife")
    print("Dry knife")
    print("Reuse knife")
    print("Cut Tomato into slices")
    print("Put away tomato")
    print("Wash Knife")
    print("Dry knife")
    print("Put away knife")
    print("Place slices of lettuce on one slice of bread")
    print("Place tomato ontop of slice of lettuce")
    print("Place slice of Cheese on top of tomato")
    print("Grab a knife")
    print("Open jar of mayonnaise")
    print("Spread mayonnaise on other slice of bread")
    print("Put away jar of mayonnaise")
    print("Combine slices of bread together")
    print("Enjoy!")

# Main
